// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: WiFiSquareLine

#ifndef __UI_WIFI_SCREEN_H
#define __UI_WIFI_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_ButtonScan;
extern lv_obj_t * ui_LabelBtnScan;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_LabelPanelStatus;
extern lv_obj_t * ui_RollerNetList;
extern lv_obj_t * ui_ButtonConnect;
extern lv_obj_t * ui_LabelBtnConnect;
extern lv_obj_t * ui_LabelAvailableNet;
extern lv_obj_t * ui_LabelTitle;
extern lv_obj_t * ui_PanelPassword;
extern lv_obj_t * ui_LabelPanelPassword;
extern lv_obj_t * ui_LabelPassword;
extern lv_obj_t * ui_PanelSearchNet;
extern lv_obj_t * ui_LabelPanelSearchNet;
extern lv_obj_t * ui_ImgPanelSearchNet;
extern lv_obj_t * ui_PanelConnecting;
extern lv_obj_t * ui_LabelPanelConnecting;
extern lv_obj_t * ui_SpinnerConnecting;
extern lv_obj_t * ui_ImgPanelConnecting;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_BtnHome;
extern lv_obj_t * ui_ImageBtnHome;
extern lv_obj_t * ui____initial_actions0;



LV_IMG_DECLARE(ui_img_search_wifi_png);    // assets\search_wifi.png
LV_IMG_DECLARE(ui_img_1656806725);    // assets\no-wifi.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets\wifi_1.png
LV_IMG_DECLARE(ui_img_home3_png);    // assets\home3.png


void ui_wifi_screen_init(void);
void ui_show_wifi_screen(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
