// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: WiFiSquareLine

#include "ui_wifi_screen.h"
#include <stdio.h>
#include "string.h"
#include "event_router.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "app_smb.h"
#include "wifi_app.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_WiFiScreen;
lv_obj_t * ui_ButtonScan;
lv_obj_t * ui_LabelBtnScan;
lv_obj_t * ui_PanelStatus;
lv_obj_t * ui_LabelPanelStatus;
lv_obj_t * ui_RollerNetList;
lv_obj_t * ui_ButtonConnect;
lv_obj_t * ui_LabelBtnConnect;
lv_obj_t * ui_LabelAvailableNet;
lv_obj_t * ui_LabelTitle;
lv_obj_t * ui_PanelPassword;
lv_obj_t * ui_LabelPanelPassword;
lv_obj_t * ui_LabelPassword;
lv_obj_t * ui_PanelSearchNet;
lv_obj_t * ui_LabelPanelSearchNet;
lv_obj_t * ui_ImgPanelSearchNet;
lv_obj_t * ui_PanelConnecting;
lv_obj_t * ui_LabelPanelConnecting;
lv_obj_t * ui_SpinnerConnecting;
lv_obj_t * ui_ImgPanelConnecting;
lv_obj_t * ui_Image2;
lv_obj_t * ui_BtnHome;
lv_obj_t * ui_ImageBtnHome;
lv_obj_t * ui_MainMenu;
lv_obj_t * ui_LabelTitle1;
lv_obj_t * ui_ButtonNetMenu;
lv_obj_t * ui_LabelBtnScan1;
lv_obj_t * ui_ButtonSharedFolderMenu;
lv_obj_t * ui_LabelBtnScan2;
lv_obj_t * ui_PanelStatus1;
lv_obj_t * ui_LabelPanelStatus1;
lv_obj_t * ui_SharedFolderMenu;
lv_obj_t * ui_ShareFolderLabelTitle;
lv_obj_t * ui_PanelStatus2;
lv_obj_t * ui_LabelPanelStatus2;
lv_obj_t * ui_ImageFolder;
lv_obj_t * ui_PanelSharedFolder;
lv_obj_t * ui_LabelSharedFolder;
lv_obj_t * ui_LabelNetwork;
lv_obj_t * ui_ButtonSharedFolderLs;
lv_obj_t * ui_SharedFolderBtnLabel1;
lv_obj_t * ui_LabelNetworkInfo;
lv_obj_t * ui_BtnHome1;
lv_obj_t * ui_ImageBtnHome1;
lv_obj_t * ui____initial_actions0;
lv_obj_t* btnm1;

const lv_img_dsc_t * home_array[2] = {&ui_img_home2_png, &ui_img_home3_png};
const lv_img_dsc_t * wifi__array[1] = {&ui_img_wifi_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

#define MAX_PASS_LEN (20)
static char password[MAX_PASS_LEN];
static char ssid[MAX_PASS_LEN];

static const char * btnm_map[] = {"1", "2", "3","\n", 
                                  "4", "5", "6","\n",
                                  "7", "8", "9","\n", 
                                  "DEL", "0", "ENTER", ""
                                 };

static void btn_matrix_cb(lv_event_t* e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t* obj = lv_event_get_target(e);
    if (code == LV_EVENT_VALUE_CHANGED) {
        uint32_t id = lv_btnmatrix_get_selected_btn(obj);
        const char* txt = lv_btnmatrix_get_btn_text(obj, id);

        printf("%s was pressed, id = %d\n", txt, id);

        if(id == 11) // "ENTER"
        {
            lv_obj_add_flag(btnm1, LV_OBJ_FLAG_HIDDEN);     /// Flags
        }
        else if(id == 9) // DEL
        {
            size_t dest_len = strlen(password);
            if(dest_len > 0)
            {
                password[dest_len - 1] = '\0';
                lv_label_set_text(ui_LabelPanelPassword, password);
            }
        }
        else
        {
            size_t dest_len = strlen(password);
            size_t max_len = sizeof(password) - dest_len - 1;

            strncat(password, txt, max_len);
            lv_label_set_text(ui_LabelPanelPassword, password);
        }
    }
}

static void on_password_cb(lv_event_t* e)
{
    switch(e->code) {
        case LV_EVENT_CLICKED:
        {
            lv_obj_clear_flag(btnm1, LV_OBJ_FLAG_HIDDEN);     /// Flags
        }
        break;
   
        default: 
        break;
    }
}



///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

static void wifi_configuration_btn(lv_event_t * e)
{
    switch(e->code) {
        case LV_EVENT_CLICKED:
        {
            event_t event = {
                .src = TASK_UI,
                .dest  = TASK_AIM,
                .id   = EVT_UI_WIFI_SELECTED,
            };
            event_router_write(&event);
        }
        break;
   
        default: 
        break;
    }
       /*Etc.*/
}


static void shared_folder_btn(lv_event_t * e)
{
    switch(e->code) {
        case LV_EVENT_CLICKED:
        {
            event_t event = {
                .src = TASK_UI,
                .dest  = TASK_AIM,
                .id   = EVT_UI_SHARED_FOLDER_SELECTED,
            };
            event_router_write(&event);  
        }
        break;

        default: 
        break;
    }
       /*Etc.*/
}

static void home_btn_cb(lv_event_t *e)
{
    switch (e->code)
    {
    case LV_EVENT_CLICKED:
    {

        event_t event = {
            .src = TASK_UI,
            .dest = TASK_AIM,
            .id = EVT_UI_HOME_SELECTED,
        };
        event_router_write(&event);
    }
    break;

    default:
        break;
    }
}

static void ls_share_folder_cb(lv_event_t *e)
{
    switch (e->code)
    {
    case LV_EVENT_CLICKED:
    {

        event_t event = {
            .src = TASK_UI,
            .dest = TASK_AIM,
            .id = EVT_UI_LS_BTN_CLICKED,
        };
        event_router_write(&event);
    }
    break;

    default:
        break;
    }
}


static void scan_network_btn_cb(lv_event_t *e)
{
    switch (e->code)
    {
    case LV_EVENT_CLICKED:
    {
        event_t event = {
            .src = TASK_UI,
            .dest  = TASK_AIM,
            .id   = EVT_UI_SCAN_BTN_CLICKED,
        };
        event_router_write(&event);
    }
    break;

    default:
        break;
    }
}


static void connect_network_btn_cb(lv_event_t *e)
{
    switch (e->code)
    {
    case LV_EVENT_CLICKED:
    {
        event_t event = {
            .src = TASK_UI,
            .dest  = TASK_AIM,
            .id   = EVT_UI_CONNECT_BTN_CLICKED,
        };
        event_router_write(&event);
    }
    break;

    default:
        break;
    }
}


///////////////////// SCREENS ////////////////////
void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonScan = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_ButtonScan, 222);
    lv_obj_set_height(ui_ButtonScan, 50);
    lv_obj_set_x(ui_ButtonScan, -118);
    lv_obj_set_y(ui_ButtonScan, 86);
    lv_obj_set_align(ui_ButtonScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ButtonScan, scan_network_btn_cb, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_LabelBtnScan = lv_label_create(ui_ButtonScan);
    lv_obj_set_width(ui_LabelBtnScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnScan, -5);
    lv_obj_set_y(ui_LabelBtnScan, 0);
    lv_obj_set_align(ui_LabelBtnScan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnScan, "SCAN");
    lv_obj_set_style_text_color(ui_LabelBtnScan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnScan, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatus = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PanelStatus, 473);
    lv_obj_set_height(ui_PanelStatus, 37);
    lv_obj_set_x(ui_PanelStatus, 2);
    lv_obj_set_y(ui_PanelStatus, 137);
    lv_obj_set_align(ui_PanelStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelStatus = lv_label_create(ui_PanelStatus);
    lv_obj_set_width(ui_LabelPanelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelStatus, 0);
    lv_obj_set_y(ui_LabelPanelStatus, 1);
    lv_obj_set_align(ui_LabelPanelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelStatus, "STATUS : ");
    lv_obj_set_style_text_font(ui_LabelPanelStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerNetList = lv_roller_create(ui_WiFiScreen);
    lv_roller_set_options(ui_RollerNetList, "SSID List\nOption 1", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerNetList, 217);
    lv_obj_set_height(ui_RollerNetList, 140);
    lv_obj_set_x(ui_RollerNetList, -118);
    lv_obj_set_y(ui_RollerNetList, -16);
    lv_obj_set_align(ui_RollerNetList, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerNetList, lv_color_hex(0x535353), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerNetList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerNetList, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_RollerNetList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_RollerNetList, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_text_color(ui_RollerNetList, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerNetList, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ButtonConnect = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_ButtonConnect, 222);
    lv_obj_set_height(ui_ButtonConnect, 50);
    lv_obj_set_x(ui_ButtonConnect, 121);
    lv_obj_set_y(ui_ButtonConnect, 86);
    lv_obj_set_align(ui_ButtonConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ButtonConnect, connect_network_btn_cb, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_LabelBtnConnect = lv_label_create(ui_ButtonConnect);
    lv_obj_set_width(ui_LabelBtnConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnConnect, -5);
    lv_obj_set_y(ui_LabelBtnConnect, 0);
    lv_obj_set_align(ui_LabelBtnConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnConnect, "CONNECT");
    lv_obj_set_style_text_color(ui_LabelBtnConnect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnConnect, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAvailableNet = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_LabelAvailableNet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAvailableNet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAvailableNet, -120);
    lv_obj_set_y(ui_LabelAvailableNet, -99);
    lv_obj_set_align(ui_LabelAvailableNet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAvailableNet, "Available Networks");
    lv_obj_set_style_text_font(ui_LabelAvailableNet, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);


    btnm1 = lv_btnmatrix_create(ui_WiFiScreen);
    lv_btnmatrix_set_map(btnm1, btnm_map);
    lv_obj_set_width(btnm1, 225);
    lv_obj_set_height(btnm1, 225);
    lv_obj_set_x(btnm1, -118);
    lv_obj_set_y(btnm1, 0);
    lv_btnmatrix_set_btn_ctrl(btnm1, 9, LV_BTNMATRIX_CTRL_CHECKABLE);
    lv_btnmatrix_set_btn_ctrl(btnm1, 11, LV_BTNMATRIX_CTRL_CHECKED);
    lv_obj_set_align(btnm1, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(btnm1, btn_matrix_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_flag(btnm1, LV_OBJ_FLAG_HIDDEN);     /// Flags


    ui_LabelTitle = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle, -6);
    lv_obj_set_y(ui_LabelTitle, -135);
    lv_obj_set_align(ui_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle, "WiFi");
    lv_obj_set_style_text_font(ui_LabelTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPassword = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PanelPassword, 217);
    lv_obj_set_height(ui_PanelPassword, 108);
    lv_obj_set_x(ui_PanelPassword, 121);
    lv_obj_set_y(ui_PanelPassword, -16);
    lv_obj_set_align(ui_PanelPassword, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPassword, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_PanelPassword, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_PanelPassword, on_password_cb, LV_EVENT_ALL, NULL);


    ui_LabelPanelPassword = lv_label_create(ui_PanelPassword);
    lv_obj_set_width(ui_LabelPanelPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelPassword, -6);
    lv_obj_set_y(ui_LabelPanelPassword, -1);
    lv_obj_set_align(ui_LabelPanelPassword, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelPassword, "|");

    ui_LabelPassword = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_LabelPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPassword, 121);
    lv_obj_set_y(ui_LabelPassword, -99);
    lv_obj_set_align(ui_LabelPassword, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPassword, "Password :");
    lv_obj_set_style_text_font(ui_LabelPassword, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSearchNet = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PanelSearchNet, 217);
    lv_obj_set_height(ui_PanelSearchNet, 106);
    lv_obj_set_x(ui_PanelSearchNet, -118);
    lv_obj_set_y(ui_PanelSearchNet, -21);
    lv_obj_set_align(ui_PanelSearchNet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSearchNet, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSearchNet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelSearchNet = lv_label_create(ui_PanelSearchNet);
    lv_obj_set_width(ui_LabelPanelSearchNet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelSearchNet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelSearchNet, -2);
    lv_obj_set_y(ui_LabelPanelSearchNet, 35);
    lv_obj_set_align(ui_LabelPanelSearchNet, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelSearchNet, "Searching ...");
    lv_obj_set_style_text_font(ui_LabelPanelSearchNet, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgPanelSearchNet = lv_img_create(ui_PanelSearchNet);
    lv_img_set_src(ui_ImgPanelSearchNet, &ui_img_search_wifi_png);
    lv_obj_set_width(ui_ImgPanelSearchNet, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_ImgPanelSearchNet, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_ImgPanelSearchNet, -6);
    lv_obj_set_y(ui_ImgPanelSearchNet, -12);
    lv_obj_set_align(ui_ImgPanelSearchNet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPanelSearchNet, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPanelSearchNet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelConnecting = lv_obj_create(ui_WiFiScreen);
    lv_obj_set_width(ui_PanelConnecting, 217);
    lv_obj_set_height(ui_PanelConnecting, 108);
    lv_obj_set_x(ui_PanelConnecting, 121);
    lv_obj_set_y(ui_PanelConnecting, -21);
    lv_obj_set_align(ui_PanelConnecting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelConnecting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelConnecting = lv_label_create(ui_PanelConnecting);
    lv_obj_set_width(ui_LabelPanelConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelConnecting, -2);
    lv_obj_set_y(ui_LabelPanelConnecting, 35);
    lv_obj_set_align(ui_LabelPanelConnecting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelConnecting, "Connecting ...");
    lv_obj_set_style_text_font(ui_LabelPanelConnecting, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerConnecting = lv_spinner_create(ui_PanelConnecting, 1000, 90);
    lv_obj_set_width(ui_SpinnerConnecting, 80);
    lv_obj_set_height(ui_SpinnerConnecting, 59);
    lv_obj_set_x(ui_SpinnerConnecting, 6);
    lv_obj_set_y(ui_SpinnerConnecting, -10);
    lv_obj_set_align(ui_SpinnerConnecting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerConnecting, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_ImgPanelConnecting = lv_img_create(ui_PanelConnecting);
    lv_img_set_src(ui_ImgPanelConnecting, &ui_img_1656806725);
    lv_obj_set_width(ui_ImgPanelConnecting, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_ImgPanelConnecting, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_ImgPanelConnecting, -3);
    lv_obj_set_y(ui_ImgPanelConnecting, -9);
    lv_obj_set_align(ui_ImgPanelConnecting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPanelConnecting, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPanelConnecting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_PanelConnecting);
    lv_img_set_src(ui_Image2, &ui_img_wifi_1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_Image2, -4);
    lv_obj_set_y(ui_Image2, -7);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnHome = lv_btn_create(ui_WiFiScreen);
    lv_obj_set_width(ui_BtnHome, 50);
    lv_obj_set_height(ui_BtnHome, 35);
    lv_obj_set_x(ui_BtnHome, -208);
    lv_obj_set_y(ui_BtnHome, -138);
    lv_obj_set_align(ui_BtnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_BtnHome, home_btn_cb, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_ImageBtnHome = lv_img_create(ui_BtnHome);
    lv_img_set_src(ui_ImageBtnHome, &ui_img_home3_png);
    lv_obj_set_width(ui_ImageBtnHome, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImageBtnHome, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImageBtnHome, -1);
    lv_obj_set_y(ui_ImageBtnHome, -1);
    lv_obj_set_align(ui_ImageBtnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnHome, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBtnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTitle1 = lv_label_create(ui_MainMenu);
    lv_obj_set_width(ui_LabelTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle1, -6);
    lv_obj_set_y(ui_LabelTitle1, -135);
    lv_obj_set_align(ui_LabelTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle1, "Main Menu");
    lv_obj_set_style_text_font(ui_LabelTitle1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonNetMenu = lv_btn_create(ui_MainMenu);
    lv_obj_set_width(ui_ButtonNetMenu, 222);
    lv_obj_set_height(ui_ButtonNetMenu, 50);
    lv_obj_set_x(ui_ButtonNetMenu, 0);
    lv_obj_set_y(ui_ButtonNetMenu, -51);
    lv_obj_set_align(ui_ButtonNetMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonNetMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonNetMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonNetMenu, wifi_configuration_btn, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_LabelBtnScan1 = lv_label_create(ui_ButtonNetMenu);
    lv_obj_set_width(ui_LabelBtnScan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnScan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnScan1, -5);
    lv_obj_set_y(ui_LabelBtnScan1, 0);
    lv_obj_set_align(ui_LabelBtnScan1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnScan1, "WiFi Configuration");
    lv_obj_set_style_text_color(ui_LabelBtnScan1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnScan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnScan1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSharedFolderMenu = lv_btn_create(ui_MainMenu);
    lv_obj_set_width(ui_ButtonSharedFolderMenu, 222);
    lv_obj_set_height(ui_ButtonSharedFolderMenu, 50);
    lv_obj_set_x(ui_ButtonSharedFolderMenu, 0);
    lv_obj_set_y(ui_ButtonSharedFolderMenu, 25);
    lv_obj_set_align(ui_ButtonSharedFolderMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSharedFolderMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSharedFolderMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ButtonSharedFolderMenu, shared_folder_btn, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_LabelBtnScan2 = lv_label_create(ui_ButtonSharedFolderMenu);
    lv_obj_set_width(ui_LabelBtnScan2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnScan2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnScan2, -5);
    lv_obj_set_y(ui_LabelBtnScan2, 0);
    lv_obj_set_align(ui_LabelBtnScan2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnScan2, "Shared Folder");
    lv_obj_set_style_text_color(ui_LabelBtnScan2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnScan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnScan2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatus1 = lv_obj_create(ui_MainMenu);
    lv_obj_set_width(ui_PanelStatus1, 473);
    lv_obj_set_height(ui_PanelStatus1, 37);
    lv_obj_set_x(ui_PanelStatus1, 2);
    lv_obj_set_y(ui_PanelStatus1, 137);
    lv_obj_set_align(ui_PanelStatus1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelStatus1 = lv_label_create(ui_PanelStatus1);
    lv_obj_set_width(ui_LabelPanelStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelStatus1, 0);
    lv_obj_set_y(ui_LabelPanelStatus1, 1);
    lv_obj_set_align(ui_LabelPanelStatus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelStatus1, "STATUS : ");
    lv_obj_set_style_text_font(ui_LabelPanelStatus1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
void ui_SharedFolderMenu_screen_init(void)
{
    ui_SharedFolderMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SharedFolderMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShareFolderLabelTitle = lv_label_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_ShareFolderLabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShareFolderLabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShareFolderLabelTitle, -6);
    lv_obj_set_y(ui_ShareFolderLabelTitle, -135);
    lv_obj_set_align(ui_ShareFolderLabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShareFolderLabelTitle, "Shared Folder");
    lv_obj_set_style_text_font(ui_ShareFolderLabelTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatus2 = lv_obj_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_PanelStatus2, 473);
    lv_obj_set_height(ui_PanelStatus2, 37);
    lv_obj_set_x(ui_PanelStatus2, 2);
    lv_obj_set_y(ui_PanelStatus2, 137);
    lv_obj_set_align(ui_PanelStatus2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPanelStatus2 = lv_label_create(ui_PanelStatus2);
    lv_obj_set_width(ui_LabelPanelStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPanelStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPanelStatus2, 0);
    lv_obj_set_y(ui_LabelPanelStatus2, 1);
    lv_obj_set_align(ui_LabelPanelStatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPanelStatus2, "STATUS : ");
    lv_obj_set_style_text_font(ui_LabelPanelStatus2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageFolder = lv_img_create(ui_SharedFolderMenu);
    lv_img_set_src(ui_ImageFolder, &ui_img_network_png);
    lv_obj_set_width(ui_ImageFolder, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_ImageFolder, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_ImageFolder, 197);
    lv_obj_set_y(ui_ImageFolder, -121);
    lv_obj_set_align(ui_ImageFolder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageFolder, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageFolder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSharedFolder = lv_obj_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_PanelSharedFolder, 352);
    lv_obj_set_height(ui_PanelSharedFolder, 163);
    lv_obj_set_x(ui_PanelSharedFolder, 53);
    lv_obj_set_y(ui_PanelSharedFolder, -4);
    lv_obj_set_align(ui_PanelSharedFolder, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSharedFolder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSharedFolder = lv_label_create(ui_PanelSharedFolder);
    lv_obj_set_width(ui_LabelSharedFolder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSharedFolder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSharedFolder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSharedFolder, "");

    ui_LabelNetwork = lv_label_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_LabelNetwork, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNetwork, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNetwork, -194);
    lv_obj_set_y(ui_LabelNetwork, 101);
    lv_obj_set_align(ui_LabelNetwork, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNetwork, "Network:");
    lv_obj_set_style_text_font(ui_LabelNetwork, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSharedFolderLs = lv_btn_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_ButtonSharedFolderLs, 100);
    lv_obj_set_height(ui_ButtonSharedFolderLs, 34);
    lv_obj_set_x(ui_ButtonSharedFolderLs, -183);
    lv_obj_set_y(ui_ButtonSharedFolderLs, -65);
    lv_obj_set_align(ui_ButtonSharedFolderLs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSharedFolderLs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSharedFolderLs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_ButtonSharedFolderLs, ls_share_folder_cb, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_SharedFolderBtnLabel1 = lv_label_create(ui_ButtonSharedFolderLs);
    lv_obj_set_width(ui_SharedFolderBtnLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SharedFolderBtnLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SharedFolderBtnLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SharedFolderBtnLabel1, "LIST CONTENT");
    lv_obj_set_style_text_color(ui_SharedFolderBtnLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SharedFolderBtnLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    char LabelNetworkInfo_str[20];
    tcpip_adapter_ip_info_t ip_info;
    tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip_info);

    smb_config_t *smb_config = app_smb_get_config();

    sprintf(LabelNetworkInfo_str,"smb://%s@%s",smb_config->user,ip4addr_ntoa(&ip_info.gw));

    ui_LabelNetworkInfo = lv_label_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_LabelNetworkInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNetworkInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNetworkInfo, 44);
    lv_obj_set_y(ui_LabelNetworkInfo, 101);
    lv_obj_set_align(ui_LabelNetworkInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNetworkInfo, LabelNetworkInfo_str);

    ui_BtnHome1 = lv_btn_create(ui_SharedFolderMenu);
    lv_obj_set_width(ui_BtnHome1, 50);
    lv_obj_set_height(ui_BtnHome1, 35);
    lv_obj_set_x(ui_BtnHome1, -208);
    lv_obj_set_y(ui_BtnHome1, -138);
    lv_obj_set_align(ui_BtnHome1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_BtnHome1, home_btn_cb, LV_EVENT_ALL, NULL );   /*Assign an event callback*/


    ui_ImageBtnHome1 = lv_img_create(ui_BtnHome1);
    lv_img_set_src(ui_ImageBtnHome1, &ui_img_home3_png);
    lv_obj_set_width(ui_ImageBtnHome1, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_ImageBtnHome1, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_ImageBtnHome1, -1);
    lv_obj_set_y(ui_ImageBtnHome1, -1);
    lv_obj_set_align(ui_ImageBtnHome1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnHome1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBtnHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}


void ui_show_wifi_screen(void)
{
    lv_disp_load_scr(ui_WiFiScreen);
    ui_set_status_msg("On WiFi Configuration");
}

void ui_show_main_screen(void)
{
    lv_disp_load_scr(ui_MainMenu);
    ui_set_status_msg("Select an Option");
}

void ui_show_folder_screen(void)
{
    lv_disp_load_scr(ui_SharedFolderMenu);
    ui_set_status_msg("On Shared Folder");

}

void ui_set_status_msg(char *msg)
{
    char buff[100];
    snprintf(buff, 100, "STATUS : %s", msg);

    // main menu
    lv_label_set_text(ui_LabelPanelStatus1, buff);

    // shared folder 
    lv_label_set_text(ui_LabelPanelStatus2, buff);

    // wifi config
    lv_label_set_text(ui_LabelPanelStatus, buff);
}

void ui_show_scanning_panel(void)
{
    lv_obj_add_flag(ui_RollerNetList, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSearchNet, LV_OBJ_FLAG_HIDDEN);
}

void ui_show_connecting_panel_in_progress(void)
{
    lv_obj_clear_flag(ui_PanelConnecting, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_SpinnerConnecting, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_PanelPassword, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_ImgPanelConnecting, LV_OBJ_FLAG_HIDDEN);     
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);     
    lv_label_set_text(ui_LabelPanelConnecting, "Connecting..");

}

void ui_show_connecting_panel_succeed(void)
{
    lv_obj_clear_flag(ui_PanelConnecting, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_ImgPanelConnecting, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SpinnerConnecting, LV_OBJ_FLAG_HIDDEN);    
    lv_obj_add_flag(ui_PanelPassword, LV_OBJ_FLAG_HIDDEN);   
    lv_label_set_text(ui_LabelPanelConnecting, "OK");
  
}

void ui_show_connecting_panel_fail(void)
{
    lv_obj_clear_flag(ui_PanelConnecting, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_ImgPanelConnecting, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SpinnerConnecting, LV_OBJ_FLAG_HIDDEN);    
    lv_obj_add_flag(ui_PanelPassword, LV_OBJ_FLAG_HIDDEN); 
    lv_label_set_text(ui_LabelPanelConnecting, "FAIL");
}


void ui_show_password_panel(void)
{
    lv_obj_add_flag(ui_SpinnerConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_add_flag(ui_PanelConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelPassword, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_LabelPanelConnecting, "");

}

void ui_show_networks_panel(void)
{
    lv_obj_add_flag(ui_PanelSearchNet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_RollerNetList, LV_OBJ_FLAG_HIDDEN);     /// Flags
}


// send string of type "Option 1\nOption 2\nOption 2"
void ui_set_scanned_networks(char *net_list)
{
    lv_roller_set_options(ui_RollerNetList, net_list, LV_ROLLER_MODE_NORMAL);
}

void ui_share_folder_set_content(char *folder_str)
{
    lv_label_set_text(ui_LabelSharedFolder, folder_str);
}

void ui_share_folder_set_sbm_name(char *smb_url)
{
    lv_label_set_text(ui_LabelNetworkInfo, smb_url);
}

char *ui_get_network_ssid(void)
{
    memset(ssid, 0, sizeof(ssid));
    lv_roller_get_selected_str(ui_RollerNetList, ssid, sizeof(ssid));
    return ssid;
}

char *ui_get_network_password(void)
{
    return lv_label_get_text(ui_LabelPanelPassword);
}



void ui_wifi_screen_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_WiFiScreen_screen_init();
    ui_MainMenu_screen_init();
    ui_SharedFolderMenu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
}
