// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: WiFiSquareLine

#ifndef _WIFISQUARELINE_UI_H
#define _WIFISQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_ButtonScan;
extern lv_obj_t * ui_LabelBtnScan;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_LabelPanelStatus;
extern lv_obj_t * ui_RollerNetList;
extern lv_obj_t * ui_ButtonConnect;
extern lv_obj_t * ui_LabelBtnConnect;
extern lv_obj_t * ui_LabelAvailableNet;
extern lv_obj_t * ui_LabelTitle;
extern lv_obj_t * ui_PanelPassword;
extern lv_obj_t * ui_LabelPanelPassword;
extern lv_obj_t * ui_LabelPassword;
extern lv_obj_t * ui_PanelSearchNet;
extern lv_obj_t * ui_LabelPanelSearchNet;
extern lv_obj_t * ui_ImgPanelSearchNet;
extern lv_obj_t * ui_PanelConnecting;
extern lv_obj_t * ui_LabelPanelConnecting;
extern lv_obj_t * ui_SpinnerConnecting;
extern lv_obj_t * ui_ImgPanelConnecting;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_BtnHome;
extern lv_obj_t * ui_ImageBtnHome;
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_LabelTitle1;
extern lv_obj_t * ui_ButtonNetMenu;
extern lv_obj_t * ui_LabelBtnScan1;
extern lv_obj_t * ui_ButtonSharedFolderMenu;
extern lv_obj_t * ui_LabelBtnScan2;
extern lv_obj_t * ui_PanelStatus1;
extern lv_obj_t * ui_LabelPanelStatus1;
extern lv_obj_t * ui_SharedFolderMenu;
extern lv_obj_t * ui_ShareFolderLabelTitle;
extern lv_obj_t * ui_PanelStatus2;
extern lv_obj_t * ui_LabelPanelStatus2;
extern lv_obj_t * ui_ImageFolder;
extern lv_obj_t * ui_PanelSharedFolder;
extern lv_obj_t * ui_LabelSharedFolder;
extern lv_obj_t * ui_LabelNetwork;
extern lv_obj_t * ui_ButtonSharedFolderLs;
extern lv_obj_t * ui_SharedFolderBtnLabel1;
extern lv_obj_t * ui_LabelNetworkInfo;
extern lv_obj_t * ui_BtnHome1;
extern lv_obj_t * ui_ImageBtnHome1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_search_wifi_png);    // assets\search_wifi.png
LV_IMG_DECLARE(ui_img_1656806725);    // assets\no-wifi.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets\wifi_1.png
LV_IMG_DECLARE(ui_img_home3_png);    // assets\home3.png
LV_IMG_DECLARE(ui_img_network_png);    // assets\network.png
LV_IMG_DECLARE(ui_img_home2_png);    // assets\home2.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
